(()=>{
 const view=document.body.dataset.view||'network';
 const qs=s=>document.querySelector(s), qsa=s=>[...document.querySelectorAll(s)];
 const colors={sensor:'#52c96d',safety:'#f4a62a',auto:'#29c7c7',control:'#7d5cf5',access:'#3b8df5',output:'#b35dea',monitor:'#66b82f',object:'#8391a8',other:'#8b9bb0'};
 const groupLabels={sensor:'感測偵測',safety:'安全偵測',auto:'自動控制',control:'控制執行',access:'門禁識別',output:'輸出設備',monitor:'監控管理',object:'物件',other:'其他'};
 const typeGroups={
  loop:'sensor',loopdetector:'sensor',infrared:'safety',radar:'sensor',directionrecognizer:'auto',signal2way:'control',signal3way:'control',barrier:'control',shutter:'control',relay:'auto',delaytimer:'auto',poweroffdelay:'auto',powerondelay:'auto',controller:'access',cardreader:'access',etag:'access',uhf:'access',intercom:'access',trafficlight:'output',laneindicator:'output',parkingdisplay:'output',beacon:'output',countdown:'output',ipcamera:'monitor',poeswitch:'monitor',powersupply:'monitor'
 };
 const demo={items:[
  ['loop_1','入口地感線圈','loop'],['loop_2','出口地感線圈','loop'],['ir_1','紅外線對射A','infrared'],['ir_2','紅外線對射B','infrared'],['dir_1','方向辨識器 LK-121','directionrecognizer'],['sig_1','雙向號誌主機','signal2way'],['bar_1','柵欄機','barrier'],['shu_1','鐵捲門','shutter'],['etag_1','ETAG讀頭','etag'],['card_1','卡機','cardreader'],['ctrl_1','門禁控制器','controller'],['int_1','對講機','intercom'],['mon_1','中央監控','ipcamera']
 ].map(([id,name,type])=>({id,name,type,di:[],do:[]})),wires:[]};
 const demoPairs=[['loop_1','dir_1','DO1','DI1'],['loop_2','dir_1','DO1','DI2'],['dir_1','sig_1','DO1','DI1'],['dir_1','bar_1','DO3','DI1'],['ir_1','bar_1','DO1','DI4'],['ir_2','shu_1','DO1','DI5'],['etag_1','ctrl_1','DO1','DI1'],['card_1','ctrl_1','DO1','DI2'],['ctrl_1','bar_1','DO1','DI1'],['ctrl_1','shu_1','DO1','DI1'],['bar_1','mon_1','DO1','DI1'],['shu_1','mon_1','DO1','DI2'],['int_1','ctrl_1','DO1','DI3']];
 demo.wires=demoPairs.map((p,i)=>({id:'w'+i,sourceId:p[0],targetId:p[1],sourcePort:p[2],targetPort:p[3]}));
 function loadSnapshot(){try{const x=window.__UTOP_RELATIONSHIP_GET_LIVE__?.();if(x?.items?.length)return x}catch{}try{const h=(window.parent&&window.parent!==window)?window.parent:window.opener;const api=h?.UTOP_RELATIONSHIP_API;const x=api?.getSnapshot?.();if(x?.items?.length)return x}catch{}try{const x=JSON.parse(sessionStorage.getItem('utop3d.relationship.live')||'null');if(x?.items?.length)return x}catch{}try{const x=JSON.parse(localStorage.getItem('utop3d.relationship.snapshot')||'null');if(x?.items?.length)return x}catch{}return demo}
 let snapshot=loadSnapshot(); let selectedId=null; let scale=1,panX=0,panY=0,drag=null; let relationStrength=0; let connectedOnly=false;
 function enrich(){snapshot.items=(snapshot.items||[]).map(i=>({...i,group:typeGroups[i.type]||(/^object_/.test(i.type)?'object':'other')}));snapshot.wires=snapshot.wires||[];snapshot.itemsById=Object.fromEntries(snapshot.items.map(i=>[i.id,i]));}
 enrich();
 function edgeType(w){const s=snapshot.itemsById[w.sourceId];const t=snapshot.itemsById[w.targetId];if(s?.group==='sensor')return'sensor';if(s?.group==='safety')return'safety';if(s?.group==='access')return'access';if(t?.group==='monitor')return'monitor';return'control'}
 function nodeDegree(id){return snapshot.wires.filter(w=>w.sourceId===id||w.targetId===id).length}
 function svgEl(tag,a={}){const e=document.createElementNS('http://www.w3.org/2000/svg',tag);Object.entries(a).forEach(([k,v])=>e.setAttribute(k,v));return e}
 const svg=qs('#graph'),layer=svgEl('g');svg.append(layer);
 const pos={};
 function layout(){posClear();if(view==='network')layoutNetwork();else if(view==='relation')layoutRelation();else if(view==='knowledge')layoutKnowledge();else layoutMindmap();render()}
 function posClear(){Object.keys(pos).forEach(k=>delete pos[k])}
 function layoutNetwork(){const W=1200,H=760;const groups=[...new Set(snapshot.items.map(i=>i.group))];groups.forEach((g,gi)=>{const arr=snapshot.items.filter(i=>i.group===g);const angle=(gi/groups.length)*Math.PI*2-Math.PI/2;const cx=W/2+Math.cos(angle)*250,cy=H/2+Math.sin(angle)*220;arr.forEach((n,j)=>{const a=(j/Math.max(1,arr.length))*Math.PI*2;pos[n.id]={x:cx+Math.cos(a)*Math.min(110,35+arr.length*9),y:cy+Math.sin(a)*Math.min(95,30+arr.length*8)}})})}
 function layoutRelation(){const W=1200;const order=['sensor','safety','auto','control','access','output','monitor','object','other'];const active=order.filter(g=>snapshot.items.some(i=>i.group===g));active.forEach((g,gi)=>{const arr=snapshot.items.filter(i=>i.group===g);const x=120+(gi/(Math.max(1,active.length-1)))*(W-240);arr.forEach((n,j)=>pos[n.id]={x,y:190+j*92})})}
 function layoutKnowledge(){const W=1200;const order=['sensor','auto','control','output','monitor','access','safety','object','other'];const trunk={x:210,y:390};order.filter(g=>snapshot.items.some(i=>i.group===g)).forEach((g,gi,all)=>{const x=460+gi%2*330;const y=95+(Math.floor(gi/2))*160;const arr=snapshot.items.filter(i=>i.group===g);arr.forEach((n,j)=>pos[n.id]={x:x+j*145,y:y+(j%2)*58})});pos.__root=trunk}
 function layoutMindmap(){const W=1200,H=760;const left=snapshot.items.filter((_,i)=>i%2===0),right=snapshot.items.filter((_,i)=>i%2===1);left.forEach((n,i)=>pos[n.id]={x:210,y:90+i*(580/Math.max(1,left.length-1))});right.forEach((n,i)=>pos[n.id]={x:990,y:90+i*(580/Math.max(1,right.length-1))});pos.__root={x:600,y:380}}
 function render(){layer.innerHTML='';layer.setAttribute('transform',`translate(${panX} ${panY}) scale(${scale})`);const search=(qs('#search')?.value||'').trim().toLowerCase();const enabled=new Set(qsa('[data-group-filter]:checked').map(x=>x.value));const visible=new Set(snapshot.items.filter(i=>(!search||i.name.toLowerCase().includes(search))&&(!enabled.size||enabled.has(i.group))).map(i=>i.id));
  if(view==='knowledge'){const root=pos.__root;const r=svgEl('circle',{cx:root.x,cy:root.y,r:58,fill:'#fff',stroke:'#7ebd8d','stroke-width':3});layer.append(r);const tx=svgEl('text',{x:root.x,y:root.y-5,'text-anchor':'middle','font-size':18,'font-weight':800,fill:'#173047'});tx.textContent='UTOP-3D';layer.append(tx);const tx2=svgEl('text',{x:root.x,y:root.y+20,'text-anchor':'middle','font-size':14,fill:'#547063'});tx2.textContent='知識樹';layer.append(tx2);}
  if(view==='mindmap'){const root=pos.__root;const rect=svgEl('rect',{x:root.x-120,y:root.y-66,width:240,height:132,rx:24,fill:'#fff',stroke:'#6d63f5','stroke-width':3});layer.append(rect);const t=svgEl('text',{x:root.x,y:root.y-5,'text-anchor':'middle','font-size':21,'font-weight':800,fill:'#222b58'});t.textContent='目前專案接線邏輯';layer.append(t);const t2=svgEl('text',{x:root.x,y:root.y+22,'text-anchor':'middle','font-size':13,fill:'#7783a3'});t2.textContent=`${snapshot.items.length} 模組｜${snapshot.wires.length} 連線`;layer.append(t2);}
  snapshot.wires.forEach(w=>{if(!visible.has(w.sourceId)||!visible.has(w.targetId))return;const edgeScore=Math.min(100,(nodeDegree(w.sourceId)+nodeDegree(w.targetId))*10);if(view==='network'&&edgeScore<relationStrength)return;const a=pos[w.sourceId],b=pos[w.targetId];if(!a||!b)return;const typ=edgeType(w);const path=svgEl('path',{d:`M${a.x},${a.y} C${(a.x+b.x)/2},${a.y} ${(a.x+b.x)/2},${b.y} ${b.x},${b.y}`,fill:'none',stroke:colors[typ]||'#789','stroke-width':selectedId&&[w.sourceId,w.targetId].includes(selectedId)?4:2,'stroke-opacity':selectedId&&![w.sourceId,w.targetId].includes(selectedId)?.16:.8,'stroke-dasharray':typ==='safety'?'8 6':''});layer.append(path)});
  if(view==='knowledge'){const root=pos.__root;snapshot.items.filter(i=>visible.has(i.id)).forEach(i=>{const p=pos[i.id];const path=svgEl('path',{d:`M${root.x+55},${root.y} C${root.x+180},${root.y} ${p.x-160},${p.y} ${p.x-70},${p.y}`,fill:'none',stroke:colors[i.group],'stroke-width':9,'stroke-opacity':.33,'stroke-linecap':'round'});layer.insertBefore(path,layer.firstChild)})}
  if(view==='mindmap'){const root=pos.__root;snapshot.items.filter(i=>visible.has(i.id)).forEach(i=>{const p=pos[i.id];const path=svgEl('path',{d:`M${root.x+(p.x<root.x?-115:115)},${root.y} C${(root.x+p.x)/2},${root.y} ${(root.x+p.x)/2},${p.y} ${p.x+(p.x<root.x?78:-78)},${p.y}`,fill:'none',stroke:colors[i.group],'stroke-width':2.5,'stroke-opacity':.85});layer.insertBefore(path,layer.firstChild)})}
  snapshot.items.filter(i=>visible.has(i.id)&&(!connectedOnly||nodeDegree(i.id)>0)).forEach(i=>drawNode(i));updateStats();updateInspector();}
 function drawNode(i){const p=pos[i.id];if(!p)return;const isSel=i.id===selectedId;const g=svgEl('g',{class:'node','data-id':i.id,transform:`translate(${p.x} ${p.y})`,style:'cursor:pointer'});const dark=view==='network';const w=view==='network'?72:150,h=view==='network'?72:54;let shape;if(view==='network'){shape=svgEl('circle',{cx:0,cy:0,r:isSel?38:34,fill:dark?'#0d1723':'#fff',stroke:colors[i.group],'stroke-width':isSel?5:3});}else{shape=svgEl('rect',{x:-w/2,y:-h/2,width:w,height:h,rx:16,fill:'#fff',stroke:colors[i.group],'stroke-width':isSel?4:2});}g.append(shape);const icon=svgEl('circle',{cx:view==='network'?0:-w/2+22,cy:view==='network'?-7:0,r:10,fill:colors[i.group]});g.append(icon);const text=svgEl('text',{x:view==='network'?0:-w/2+42,y:view==='network'?54:5,'text-anchor':view==='network'?'middle':'start','font-size':view==='network'?15:14,'font-weight':700,fill:dark?'#edf5ff':'#19314d'});text.textContent=i.name.length>18?i.name.slice(0,18)+'…':i.name;g.append(text);if(view==='network'){const d=svgEl('text',{x:0,y:15,'text-anchor':'middle','font-size':12,fill:colors[i.group]});d.textContent=nodeDegree(i.id);g.append(d)}g.addEventListener('click',e=>{e.stopPropagation();selectedId=i.id;render()});g.addEventListener('mousemove',e=>showTip(e,`${i.name}\n${groupLabels[i.group]}｜${nodeDegree(i.id)} 條關聯`));g.addEventListener('mouseleave',hideTip);layer.append(g)}
 function updateStats(){qs('#statModules').textContent=snapshot.items.length;qs('#statLinks').textContent=snapshot.wires.length;qs('#statGroups').textContent=new Set(snapshot.items.map(i=>i.group)).size;qs('#statSelected').textContent=selectedId?nodeDegree(selectedId):'—'}
 function updateInspector(){const box=qs('#selectedBox'),links=qs('#linkList');const i=snapshot.itemsById[selectedId];if(!i){box.innerHTML='<div class="empty">點選任何模組，查看它連結了甚麼。</div>';links.innerHTML='';return}const io=[...(i.di||[]).map(x=>'DI '+(Array.isArray(x)?x[1]:x)),...(i.do||[]).map(x=>'DO '+(Array.isArray(x)?x[1]:x))].slice(0,8);box.innerHTML=`<h3>${esc(i.name)}</h3><span class="chip">${esc(groupLabels[i.group])}</span><span class="chip">${esc(i.type)}</span>${io.length?`<p class="hint">${io.map(esc).join('<br>')}</p>`:''}`;const ws=snapshot.wires.filter(w=>w.sourceId===i.id||w.targetId===i.id);links.innerHTML=ws.length?ws.map(w=>{const out=w.sourceId===i.id,target=snapshot.itemsById[out?w.targetId:w.sourceId];return `<div class="link-row"><b>${out?'→':'←'} ${esc(target?.name||'未知模組')}</b><br><span class="hint">${esc(out?w.sourcePort:w.targetPort)} → ${esc(out?w.targetPort:w.sourcePort)}</span></div>`}).join(''):'<div class="empty">目前沒有接線</div>'}
 function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
 function showTip(e,t){const tip=qs('#tooltip');tip.textContent=t;tip.style.display='block';tip.style.left=(e.clientX+12)+'px';tip.style.top=(e.clientY+12)+'px'}function hideTip(){qs('#tooltip').style.display='none'}
 function fit(){scale=1;panX=0;panY=0;layer.setAttribute('transform','translate(0 0) scale(1)')}
 svg.addEventListener('wheel',e=>{e.preventDefault();scale=Math.max(.4,Math.min(2.4,scale*(e.deltaY<0?1.1:.9)));render()},{passive:false});svg.addEventListener('pointerdown',e=>{if(e.target.closest?.('.node'))return;drag={x:e.clientX,y:e.clientY,px:panX,py:panY};svg.setPointerCapture(e.pointerId)});svg.addEventListener('pointermove',e=>{if(!drag)return;panX=drag.px+e.clientX-drag.x;panY=drag.py+e.clientY-drag.y;layer.setAttribute('transform',`translate(${panX} ${panY}) scale(${scale})`)});svg.addEventListener('pointerup',()=>drag=null);svg.addEventListener('click',()=>{selectedId=null;render()});
 
 const strength=qs('#strengthInput');if(strength)strength.addEventListener('input',()=>{relationStrength=Number(strength.value)||0;render()});
 qsa('[data-action]').forEach(b=>b.addEventListener('click',()=>{
  const a=b.dataset.action;
  if(a==='connected-only'){connectedOnly=true;render();}
  if(a==='show-all'){connectedOnly=false;qsa('[data-group-filter]').forEach(x=>x.checked=true);render();}
  if(a==='flow-only'){connectedOnly=false;const keep=new Set(['sensor','auto','control','output','monitor']);qsa('[data-group-filter]').forEach(x=>x.checked=keep.has(x.value));render();}
  if(a==='control-chain'){connectedOnly=true;const keep=new Set(['sensor','safety','auto','control','access','output','monitor']);qsa('[data-group-filter]').forEach(x=>x.checked=keep.has(x.value));render();}
  if(a==='auto-layout'){posClear();layout();fit();render();}
 }));
qsa('[data-group-filter]').forEach(x=>x.addEventListener('change',render));qs('#search').addEventListener('input',render);qs('#fitBtn').onclick=()=>{fit();render()};qs('#reloadBtn').onclick=()=>{snapshot=loadSnapshot();enrich();selectedId=null;layout()};qs('#backBtn').onclick=()=>{try{if(window.opener&&!window.opener.closed){window.opener.focus();const dlg=window.opener.document.getElementById('wiringDialog');if(dlg&&!dlg.open)dlg.showModal();return}}catch{}location.href='../../index.html'};qs('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify({view,snapshot},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`UTOP-${view}-relations.json`;a.click();URL.revokeObjectURL(a.href)};
 layout();
})();
