import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';

const view=document.body.dataset.view||'network';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const colors={sensor:0x52c96d,safety:0xf4a62a,auto:0x29c7c7,control:0x7d5cf5,access:0x3b8df5,output:0xb35dea,monitor:0x66b82f,object:0x8391a8,other:0x8b9bb0};
const colorCss=Object.fromEntries(Object.entries(colors).map(([k,v])=>[k,'#'+v.toString(16).padStart(6,'0')]));
const groupLabels={sensor:'感測偵測',safety:'安全偵測',auto:'自動控制',control:'控制執行',access:'門禁識別',output:'輸出設備',monitor:'監控管理',object:'物件',other:'其他'};
const typeGroups={loop:'sensor',loopdetector:'sensor',infrared:'safety',radar:'sensor',directionrecognizer:'auto',signal2way:'control',signal3way:'control',barrier:'control',shutter:'control',relay:'auto',delaytimer:'auto',poweroffdelay:'auto',powerondelay:'auto',controller:'access',cardreader:'access',etag:'access',uhf:'access',intercom:'access',trafficlight:'output',laneindicator:'output',parkingdisplay:'output',beacon:'output',countdown:'output',ipcamera:'monitor',poeswitch:'monitor',powersupply:'monitor'};
const demo={items:[['loop_1','入口地感線圈','loop'],['loop_2','出口地感線圈','loop'],['ir_1','紅外線對射A','infrared'],['ir_2','紅外線對射B','infrared'],['dir_1','方向辨識器 LK-121','directionrecognizer'],['sig_1','雙向號誌主機','signal2way'],['bar_1','柵欄機','barrier'],['shu_1','鐵捲門','shutter'],['etag_1','ETAG讀頭','etag'],['card_1','卡機','cardreader'],['ctrl_1','門禁控制器','controller'],['int_1','對講機','intercom'],['mon_1','中央監控','ipcamera']].map(([id,name,type])=>({id,name,type,di:[],do:[]})),wires:[]};
const demoPairs=[['loop_1','dir_1','DO1','DI1'],['loop_2','dir_1','DO1','DI2'],['dir_1','sig_1','DO1','DI1'],['dir_1','bar_1','DO3','DI1'],['ir_1','bar_1','DO1','DI4'],['ir_2','shu_1','DO1','DI5'],['etag_1','ctrl_1','DO1','DI1'],['card_1','ctrl_1','DO1','DI2'],['ctrl_1','bar_1','DO1','DI1'],['ctrl_1','shu_1','DO1','DI1'],['bar_1','mon_1','DO1','DI1'],['shu_1','mon_1','DO1','DI2'],['int_1','ctrl_1','DO1','DI3']];
demo.wires=demoPairs.map((p,i)=>({id:'w'+i,sourceId:p[0],targetId:p[1],sourcePort:p[2],targetPort:p[3]}));
function loadSnapshot(){try{const api=window.opener?.UTOP_RELATIONSHIP_API;if(api?.getSnapshot)return api.getSnapshot()}catch{}try{const x=JSON.parse(localStorage.getItem('utop3d.relationship.snapshot')||'null');if(x?.items?.length)return x}catch{}return structuredClone(demo)}
let snapshot=loadSnapshot(),selectedId=null,relationStrength=0,connectedOnly=false;
let forceEnabled=view==='network', forceTemperature=1, forceSettledFrames=0; const pinnedNodes=new Set();
const velocities=new Map();
function enrich(){snapshot.items=(snapshot.items||[]).map(i=>({...i,group:typeGroups[i.type]||(/^object_/.test(i.type)?'object':'other')}));snapshot.wires=snapshot.wires||[];snapshot.itemsById=Object.fromEntries(snapshot.items.map(i=>[i.id,i]));} enrich();
const container=$('#graph');
const scene=new THREE.Scene();
scene.background=new THREE.Color(view==='network'?0x071019:0xf7f9fd);
scene.fog=new THREE.Fog(scene.background,28,90);
const camera=new THREE.PerspectiveCamera(48,1,.1,200);
camera.position.set(0,16,34);
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;container.appendChild(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.08;controls.screenSpacePanning=true;controls.minDistance=6;controls.maxDistance=95;controls.target.set(0,0,0);
scene.add(new THREE.AmbientLight(0xffffff,1.7));const dl=new THREE.DirectionalLight(0xffffff,2);dl.position.set(8,18,12);scene.add(dl);
const grid=new THREE.GridHelper(70,35,view==='network'?0x203044:0xdce5f2,view==='network'?0x172436:0xe9eef7);grid.rotation.x=0;grid.position.y=-7;scene.add(grid);
const graphGroup=new THREE.Group();scene.add(graphGroup);
const positionStorageKey=`utop3d.relationship3d.positions.${view}`;
function readSavedPositions(){try{return JSON.parse(localStorage.getItem(positionStorageKey)||'{}')||{}}catch{return {}}}
function savePositions(){try{localStorage.setItem(positionStorageKey,JSON.stringify(Object.fromEntries([...nodeMeshes].map(([id,g])=>[id,{x:g.position.x,y:g.position.y,z:g.position.z}]))))}catch{}}
const nodeMeshes=new Map(), labels=new Map(), edgeLines=[];const nodePositions=new Map();
const neighborCache=new Map();
const raycaster=new THREE.Raycaster(), pointer=new THREE.Vector2();let dragNode=null,dragOffset=new THREE.Vector3();const dragPlane=new THREE.Plane();
function degree(id){return snapshot.wires.filter(w=>w.sourceId===id||w.targetId===id).length}
function neighbors(id){if(neighborCache.has(id))return neighborCache.get(id);const set=new Set();for(const w of snapshot.wires){if(w.sourceId===id)set.add(w.targetId);if(w.targetId===id)set.add(w.sourceId)}neighborCache.set(id,set);return set}
function connectedWithinTwo(id){const out=new Set([id]);for(const a of neighbors(id)){out.add(a);for(const b of neighbors(a))out.add(b)}return out}
function edgeType(w){const s=snapshot.itemsById[w.sourceId],t=snapshot.itemsById[w.targetId];if(s?.group==='sensor')return'sensor';if(s?.group==='safety')return'safety';if(s?.group==='access')return'access';if(t?.group==='monitor')return'monitor';return'control'}
function spriteLabel(text,group){const c=document.createElement('canvas'),ctx=c.getContext('2d');const fs=30;c.width=512;c.height=96;ctx.clearRect(0,0,c.width,c.height);ctx.font=`700 ${fs}px Microsoft JhengHei`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle=view==='network'?'rgba(7,16,25,.88)':'rgba(255,255,255,.92)';roundRect(ctx,8,8,496,80,18);ctx.fill();ctx.strokeStyle=colorCss[group];ctx.lineWidth=4;ctx.stroke();ctx.fillStyle=view==='network'?'#edf5ff':'#173047';ctx.fillText(text.length>22?text.slice(0,22)+'…':text,256,48);const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;const sp=new THREE.Sprite(new THREE.SpriteMaterial({map:tex,transparent:true,depthTest:false}));sp.scale.set(6.8,1.28,1);sp.renderOrder=10;return sp}
function roundRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.roundRect?ctx.roundRect(x,y,w,h,r):(ctx.rect(x,y,w,h));}
function clearGraph(){neighborCache.clear();for(const o of [...graphGroup.children]){graphGroup.remove(o);o.geometry?.dispose?.();if(o.material?.map)o.material.map.dispose();o.material?.dispose?.()}nodeMeshes.clear();labels.clear();edgeLines.length=0}
function layout(){const items=snapshot.items;const saved=readSavedPositions();const groups=[...new Set(items.map(i=>i.group))];
 if(view==='network'){groups.forEach((g,gi)=>{const arr=items.filter(i=>i.group===g);const a=gi/Math.max(1,groups.length)*Math.PI*2;const center=new THREE.Vector3(Math.cos(a)*9,(gi%3-1)*2.6,Math.sin(a)*9);arr.forEach((n,j)=>{const seed=(j+1)*1.618;const aa=seed*Math.PI*2;const r=2.2+((j*37)%11)/11*2.6;nodePositions.set(n.id,center.clone().add(new THREE.Vector3(Math.cos(aa)*r,((j*17)%7-3)*.55,Math.sin(aa)*r)))})})}
 else if(view==='relation'){const order=['sensor','safety','auto','control','access','output','monitor','object','other'];const active=order.filter(g=>items.some(i=>i.group===g));active.forEach((g,gi)=>{const arr=items.filter(i=>i.group===g);const z=(gi-(active.length-1)/2)*5;arr.forEach((n,j)=>nodePositions.set(n.id,new THREE.Vector3((j-(arr.length-1)/2)*5,(gi%2)*2-1,z)))})}
 else if(view==='knowledge'){const order=['sensor','safety','auto','control','access','output','monitor','object','other'];order.forEach((g,gi)=>{const arr=items.filter(i=>i.group===g);const angle=(gi/order.length)*Math.PI*2;arr.forEach((n,j)=>nodePositions.set(n.id,new THREE.Vector3(Math.cos(angle)*(8+j*2),-1+j*2.3,Math.sin(angle)*(8+j*2))))})}
 else {const left=items.filter((_,i)=>i%2===0),right=items.filter((_,i)=>i%2===1);left.forEach((n,i)=>nodePositions.set(n.id,new THREE.Vector3(-10,(i-(left.length-1)/2)*3,(i%3-1)*3)));right.forEach((n,i)=>nodePositions.set(n.id,new THREE.Vector3(10,(i-(right.length-1)/2)*3,(i%3-1)*3))}
 for(const item of items){const q=saved[item.id];if(q&&Number.isFinite(q.x)&&Number.isFinite(q.y)&&Number.isFinite(q.z))nodePositions.set(item.id,new THREE.Vector3(q.x,q.y,q.z));}
}
function createNode(item){const group=new THREE.Group();const d=degree(item.id);const nodeScale=view==='network'?Math.min(2.25,.82+Math.sqrt(Math.max(1,d))*.27):1;const mat=new THREE.MeshStandardMaterial({color:colors[item.group],roughness:view==='network'?.24:.38,metalness:view==='network'?.22:.15,emissive:colors[item.group],emissiveIntensity:view==='network'?.42:.08,transparent:true,opacity:1});let geo;if(view==='network')geo=new THREE.IcosahedronGeometry(1.0,3);else geo=new THREE.BoxGeometry(2.7,1.45,.9);const mesh=new THREE.Mesh(geo,mat);mesh.scale.setScalar(nodeScale);mesh.userData.nodeId=item.id;mesh.userData.baseScale=nodeScale;group.add(mesh);const ringRadius=view==='network'?1.18*nodeScale:1.65;const ring=new THREE.Mesh(new THREE.TorusGeometry(ringRadius,.045,10,64),new THREE.MeshBasicMaterial({color:colors[item.group],transparent:true,opacity:view==='network'?.36:.52,depthWrite:false}));ring.rotation.x=Math.PI/2;ring.userData.ring=true;group.add(ring);if(view==='network'){const halo=new THREE.Mesh(new THREE.SphereGeometry(1.35*nodeScale,20,20),new THREE.MeshBasicMaterial({color:colors[item.group],transparent:true,opacity:.055,depthWrite:false,blending:THREE.AdditiveBlending}));halo.userData.halo=true;group.add(halo)}const sp=spriteLabel(item.name,item.group);sp.position.set(0,view==='network'?1.55+nodeScale*.55:1.45,0);if(view==='network')sp.scale.multiplyScalar(.84+Math.min(.34,d*.025));group.add(sp);group.position.copy(nodePositions.get(item.id)||new THREE.Vector3());graphGroup.add(group);nodeMeshes.set(item.id,group);labels.set(item.id,sp);if(!velocities.has(item.id))velocities.set(item.id,new THREE.Vector3())}
function createEdge(w){const a=nodePositions.get(w.sourceId),b=nodePositions.get(w.targetId);if(!a||!b)return;const curve=new THREE.CatmullRomCurve3([a.clone(),a.clone().lerp(b,.33).add(new THREE.Vector3(0,1.3,0)),a.clone().lerp(b,.66).add(new THREE.Vector3(0,-1.0,0)),b.clone()]);const geo=new THREE.BufferGeometry().setFromPoints(curve.getPoints(36));const line=new THREE.Line(geo,new THREE.LineBasicMaterial({color:colors[edgeType(w)]||0x789abc,transparent:true,opacity:view==='network'?.52:.78,depthWrite:false}));line.userData.wire=w;graphGroup.add(line);edgeLines.push(line)}
function rebuild(){clearGraph();layout();const search=($('#search')?.value||'').trim().toLowerCase();const enabled=new Set($$('[data-group-filter]:checked').map(x=>x.value));for(const item of snapshot.items){if(search&&!item.name.toLowerCase().includes(search))continue;if(enabled.size&&!enabled.has(item.group))continue;if(connectedOnly&&degree(item.id)===0)continue;createNode(item)}for(const w of snapshot.wires){if(!nodeMeshes.has(w.sourceId)||!nodeMeshes.has(w.targetId))continue;if(view==='network'){const score=Math.min(100,(degree(w.sourceId)+degree(w.targetId))*10);if(score<relationStrength)continue}createEdge(w)}updateStats();updateInspector();if(view==='network'){forceTemperature=Math.max(forceTemperature,.72);forceSettledFrames=0;applyFocusVisuals()}}
function updateEdges(){for(const line of edgeLines){const w=line.userData.wire,a=nodeMeshes.get(w.sourceId)?.position,b=nodeMeshes.get(w.targetId)?.position;if(!a||!b)continue;const curve=new THREE.CatmullRomCurve3([a.clone(),a.clone().lerp(b,.33).add(new THREE.Vector3(0,1.3,0)),a.clone().lerp(b,.66).add(new THREE.Vector3(0,-1,0)),b.clone()]);line.geometry.dispose();line.geometry=new THREE.BufferGeometry().setFromPoints(curve.getPoints(36))}}
function updateStats(){$('#statModules').textContent=snapshot.items.length;$('#statLinks').textContent=snapshot.wires.length;$('#statGroups').textContent=new Set(snapshot.items.map(i=>i.group)).size;$('#statSelected').textContent=selectedId?degree(selectedId):'—'}
function updateInspector(){const box=$('#selectedBox'),links=$('#linkList'),i=snapshot.itemsById[selectedId];box?.classList.toggle('focused',!!i);if(!i){box.innerHTML='<div class="empty">點選任何模組，查看它連結了甚麼。</div>';links.innerHTML='';return}box.innerHTML=`<h3>${esc(i.name)}</h3><span class="chip">${groupLabels[i.group]}</span><span class="chip">${esc(i.type||'module')}</span><p class="hint">3D 位置：${fmt(nodeMeshes.get(i.id)?.position)}</p>`;const rs=snapshot.wires.filter(w=>w.sourceId===i.id||w.targetId===i.id);links.innerHTML=rs.map(w=>{const outgoing=w.sourceId===i.id,other=snapshot.itemsById[outgoing?w.targetId:w.sourceId];return `<div class="link-row"><b>${outgoing?'→':'←'} ${esc(other?.name||'未知模組')}</b><br><span class="hint">${esc(outgoing?w.sourcePort:w.targetPort)} → ${esc(outgoing?w.targetPort:w.sourcePort)}</span></div>`}).join('')||'<div class="empty">目前沒有接線</div>'}
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));const fmt=p=>p?`${p.x.toFixed(1)}, ${p.y.toFixed(1)}, ${p.z.toFixed(1)}`:'—';
function groupCenter(group){const order=['sensor','safety','auto','control','access','output','monitor','object','other'];const i=Math.max(0,order.indexOf(group)),a=i/order.length*Math.PI*2;return new THREE.Vector3(Math.cos(a)*8.5,((i%3)-1)*2.3,Math.sin(a)*8.5)}
function stepForce(){if(view!=='network'||!forceEnabled||dragNode)return;const ids=[...nodeMeshes.keys()];if(!ids.length)return;const alpha=Math.max(.018,forceTemperature);const repulsion=16*alpha,spring=.012*alpha,cluster=.006*alpha,centerPull=.0018*alpha;for(const id of ids){if(pinnedNodes.has(id))continue;const v=velocities.get(id)||new THREE.Vector3();v.multiplyScalar(.88);velocities.set(id,v)}for(let i=0;i<ids.length;i++){const ai=ids[i],a=nodeMeshes.get(ai);if(!a||pinnedNodes.has(ai))continue;const va=velocities.get(ai);for(let j=i+1;j<ids.length;j++){const bi=ids[j],b=nodeMeshes.get(bi);if(!b)continue;const delta=a.position.clone().sub(b.position);let dist2=Math.max(.7,delta.lengthSq());delta.normalize();const f=repulsion/dist2;if(!pinnedNodes.has(ai))va.addScaledVector(delta,f);if(!pinnedNodes.has(bi))(velocities.get(bi)||new THREE.Vector3()).addScaledVector(delta,-f)}}for(const w of snapshot.wires){const a=nodeMeshes.get(w.sourceId),b=nodeMeshes.get(w.targetId);if(!a||!b)continue;const delta=b.position.clone().sub(a.position);const dist=Math.max(.01,delta.length());const ideal=5.4+Math.min(3,(degree(w.sourceId)+degree(w.targetId))*.09);const f=(dist-ideal)*spring;delta.normalize();if(!pinnedNodes.has(w.sourceId))velocities.get(w.sourceId)?.addScaledVector(delta,f);if(!pinnedNodes.has(w.targetId))velocities.get(w.targetId)?.addScaledVector(delta,-f)}for(const id of ids){if(pinnedNodes.has(id))continue;const g=nodeMeshes.get(id),item=snapshot.itemsById[id],v=velocities.get(id);if(!g||!v||!item)continue;const gc=groupCenter(item.group);v.addScaledVector(gc.clone().sub(g.position),cluster);v.addScaledVector(g.position.clone().multiplyScalar(-1),centerPull);const max=.22+alpha*.22;if(v.length()>max)v.setLength(max);g.position.add(v);nodePositions.set(id,g.position.clone())}updateEdges();forceTemperature*=.992;if(forceTemperature<.022)forceSettledFrames++;else forceSettledFrames=0;if(forceSettledFrames>240)forceTemperature=.018}
function applyFocusVisuals(){if(view!=='network')return;const visible=selectedId?connectedWithinTwo(selectedId):null;const direct=selectedId?neighbors(selectedId):null;for(const [id,g] of nodeMeshes){const mesh=g.children.find(o=>o.userData?.nodeId===id),ring=g.children.find(o=>o.userData?.ring),halo=g.children.find(o=>o.userData?.halo),label=labels.get(id);const isSel=id===selectedId,isDirect=!!direct?.has(id),isNear=!!visible?.has(id);const fade=selectedId&&!isNear; if(mesh?.material){mesh.material.opacity=fade?.14:1;mesh.material.emissiveIntensity=isSel?.95:isDirect?.65:.38}if(ring?.material)ring.material.opacity=fade?.05:isSel?.9:isDirect?.55:.28;if(halo?.material)halo.material.opacity=fade?.01:isSel?.16:isDirect?.09:.04;if(label?.material)label.material.opacity=fade?.18:1}
for(const line of edgeLines){const w=line.userData.wire;const hit=selectedId&&(w.sourceId===selectedId||w.targetId===selectedId);const near=selectedId&&(visible?.has(w.sourceId)&&visible?.has(w.targetId));line.material.opacity=selectedId?(hit?.96:near?.24:.035):.52}}
function setSelected(id){selectedId=id;applyFocusVisuals();updateStats();updateInspector()}

function resize(){const r=container.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=Math.max(.1,r.width/r.height);camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(container);resize();
function pointerNdc(e){const r=renderer.domElement.getBoundingClientRect();pointer.x=((e.clientX-r.left)/r.width)*2-1;pointer.y=-((e.clientY-r.top)/r.height)*2+1;raycaster.setFromCamera(pointer,camera)}
function nodeIntersections(){return raycaster.intersectObjects([...nodeMeshes.values()].flatMap(g=>g.children.filter(o=>o.isMesh)),false)}
renderer.domElement.addEventListener('pointerdown',e=>{if(e.button!==0)return;pointerNdc(e);const hit=nodeIntersections()[0];if(!hit)return;const id=hit.object.userData.nodeId||hit.object.parent?.children.find(x=>x.userData?.nodeId)?.userData.nodeId;const group=[...nodeMeshes.entries()].find(([,g])=>g.children.includes(hit.object))?.[1];if(!group)return;dragNode=group;selectedId=[...nodeMeshes.entries()].find(([,g])=>g===group)?.[0]||null;if(selectedId){pinnedNodes.add(selectedId);setSelected(selectedId)}controls.enabled=false;const n=camera.getWorldDirection(new THREE.Vector3()).normalize();dragPlane.setFromNormalAndCoplanarPoint(n,group.position);const pt=new THREE.Vector3();if(raycaster.ray.intersectPlane(dragPlane,pt))dragOffset.copy(group.position).sub(pt);renderer.domElement.setPointerCapture(e.pointerId);applyFocusVisuals();updateInspector()});
renderer.domElement.addEventListener('pointermove',e=>{if(!dragNode)return;pointerNdc(e);const pt=new THREE.Vector3();if(raycaster.ray.intersectPlane(dragPlane,pt)){dragNode.position.copy(pt.add(dragOffset));const id=[...nodeMeshes.entries()].find(([,g])=>g===dragNode)?.[0];if(id)nodePositions.set(id,dragNode.position.clone());updateEdges();updateInspector()}});
function endDrag(e){if(!dragNode)return;savePositions();forceTemperature=Math.max(forceTemperature,.18);dragNode=null;controls.enabled=true;try{renderer.domElement.releasePointerCapture(e.pointerId)}catch{}}
renderer.domElement.addEventListener('pointerup',endDrag);renderer.domElement.addEventListener('pointercancel',endDrag);
renderer.domElement.addEventListener('dblclick',e=>{pointerNdc(e);const hit=nodeIntersections()[0];if(!hit)return;const pair=[...nodeMeshes.entries()].find(([,g])=>g.children.includes(hit.object));if(pair){setSelected(pair[0]);controls.target.copy(pair[1].position)}});
renderer.domElement.addEventListener('click',e=>{if(dragNode)return;pointerNdc(e);if(!nodeIntersections()[0]&&selectedId){setSelected(null)}});
function fit(){camera.position.set(0,16,34);controls.target.set(0,0,0);controls.update()}
$('#fitBtn').onclick=fit;$('#reloadBtn').onclick=()=>{snapshot=loadSnapshot();enrich();selectedId=null;nodePositions.clear();rebuild();fit()};$('#backBtn').onclick=()=>{try{if(window.opener&&!window.opener.closed){window.opener.focus();const dlg=window.opener.document.getElementById('wiringDialog');if(dlg&&!dlg.open)dlg.showModal();return}}catch{}location.href='../../index.html'};$('#exportBtn').onclick=()=>{const positions=Object.fromEntries([...nodeMeshes].map(([id,g])=>[id,{x:g.position.x,y:g.position.y,z:g.position.z}]));const blob=new Blob([JSON.stringify({version:'5.1.3.61',view,snapshot,positions},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`UTOP-${view}-3d-relations.json`;a.click();URL.revokeObjectURL(a.href)};
const forceBtn=$('#forceBtn');if(forceBtn)forceBtn.onclick=()=>{forceEnabled=!forceEnabled;forceBtn.textContent=`◎ 力導向：${forceEnabled?'開':'關'}`;forceBtn.classList.toggle('active-toggle',forceEnabled);if(forceEnabled){forceTemperature=.9;forceSettledFrames=0}};const releasePinsBtn=$('#releasePinsBtn');if(releasePinsBtn)releasePinsBtn.onclick=()=>{pinnedNodes.clear();try{localStorage.removeItem(positionStorageKey)}catch{}forceTemperature=1;forceSettledFrames=0};
$('#search').addEventListener('input',rebuild);$$('[data-group-filter]').forEach(x=>x.addEventListener('change',rebuild));const strength=$('#strengthInput');if(strength)strength.addEventListener('input',()=>{relationStrength=Number(strength.value)||0;rebuild()});$$('[data-action]').forEach(b=>b.addEventListener('click',()=>{const a=b.dataset.action;if(a==='connected-only'){connectedOnly=true;rebuild()}if(a==='show-all'){connectedOnly=false;$$('[data-group-filter]').forEach(x=>x.checked=true);rebuild()}if(a==='flow-only'){connectedOnly=false;const keep=new Set(['sensor','auto','control','output','monitor']);$$('[data-group-filter]').forEach(x=>x.checked=keep.has(x.value));rebuild()}if(a==='control-chain'){connectedOnly=true;const keep=new Set(['sensor','safety','auto','control','access','output','monitor']);$$('[data-group-filter]').forEach(x=>x.checked=keep.has(x.value));rebuild()}if(a==='auto-layout'){try{localStorage.removeItem(positionStorageKey)}catch{}pinnedNodes.clear();nodePositions.clear();forceTemperature=1;forceSettledFrames=0;rebuild();fit()}}));
const help=document.createElement('div');help.className='drag-help';help.textContent='拖曳模組可搬移｜左鍵旋轉／右鍵平移／滾輪縮放｜雙擊模組置中';container.parentElement.append(help);
function animate(){requestAnimationFrame(animate);stepForce();if(view==='network'&&selectedId){const g=nodeMeshes.get(selectedId),halo=g?.children.find(o=>o.userData?.halo);if(halo){const p=1+Math.sin(performance.now()*.004)*.055;halo.scale.setScalar(p)}}controls.update();renderer.render(scene,camera)}rebuild();fit();animate();
